version: "3.8"
services:
  app:
    image: bitnami/laravel:latest
    ports:
      - "8000:8000"
      - "5173:5173" # Vite用のポートを追加
    volumes:
      - ./src:/app
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=laravelpassword
    depends_on:
      - db
    command: php /app/artisan serve --host=0.0.0.0 --port=8000
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
